[features]
seeds = false
skip-lint = false
[programs.localnet]
counter_program = "2GzbhseMLbLUXNL7oSZJ1mYQSuCgPWoJUPaZmuQD1Q7d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
